### ISSUE TITLE
how to generate the "penguins-speaker.html" file?

### ISSUE THREAD

**Issue by liamxg** [mine-cetinkaya-rundel/quarto-for-academics#1]
Dear @mine-cetinkaya-rundel,

Could you please tell me how to generate the "penguins-speaker.html" file, thanks.

Best,
Liam

**Comment by mine-cetinkaya-rundel** [comment]
You need to set `multiplex: true`. See https://quarto.org/docs/presentations/revealjs/presenting.html#multiplex for more.
